imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver:     orm                                  # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                                 # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    ShareMyDocs\UserBundle\Entity\User   # La classe de l'entité User que nous utilisons

# imag_ldap Configuration
imag_ldap:
    client:
        host: http://192.168.1.84
        port: 389
#       version: 3 # Optional
#       username: foo # Optional
#       password: bar # Optional
#       network_timeout: 10 # Optional
#       referrals_enabled: true # Optional
#       bind_username_before: true # Optional
#       skip_roles: false # Optional

    user:
        base_dn: ou=person,dc=tse,dc=fr
#       filter: (&(foo=bar)(ObjectClass=Person)) #Optional
        name_attribute: uid
    role:
        base_dn: ou=groupes, dc=tse, dc=fr
#       filter: (ou=group) #Optional
        name_attribute: cn
        user_attribute: member
        user_id:  dn

#  user_class: IMAG\LdapBundle\User\LdapUser # Optional