parameters:
#    rmo_platform.example.class: RMO\PlatformBundle\Example

services:
#    rmo_platform.example:
#        class: %rmo_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]